### PR TITLE
Italicize ;addquills and ;removequills

### PR DESCRIPTION
**Pull request by franciscoatwi**

### CODE REVIEW

**Comment by franciscoatwi** [comment]
Reason: Avoid double highlight.

**Comment by Asheviere** [comment]
Is this really a big deal tho

**Comment by franciscoatwi** [comment]
I mean its kinda annoying to get both a highlight and PM

**Comment by franciscoatwi** [comment]
But its up to you and myst.

**Comment by Mystifi** [comment]
Finally putting in my two cents here instead of PMs with Aurolux, but if it's too big of a deal, I can just tell the staff to use the command in PMs (since it's usable anywhere). The bot PMs the user the notification as well just in case the staff member used the command in PMs, but I can just add a check to prevent it from doing that if the command was used in chat. Is that alright?

**Comment by franciscoatwi** [comment]
Yeah thats cool! ^_^ I'll go ahead and close.

**Comment by Mystifi** [comment]
Done in 103606d.

**Pull request closed without merging**
